### ISSUE TITLE
Dashboard: Edit Projects gives permission denied

### ISSUE THREAD

**Issue by tkivela** [Kruemelkatze/vscode-dashboard#1]
Hi,

Thanks you for excellent plugin. I'm using the plugin with Ubuntu 18.04 and selecting "Dashboard: Edit Projects" I get an error:
EACCES: permission denied, mkdir '/var/local/vscode-dashboard'

No screen shows up after the error so the error prevents editing of dashboard.

**Comment by Kruemelkatze** [comment]
Hey!

This is probably a Linux-only problem. I'll setup a system and have a look into this!

Thanks for reporting :)

**Comment by GammaGames** [comment]
I had this problem too, I made `/var/local/vscode-dashboard/Dashboard Projects.json` and gave it `777` permissions. The extension works fine now, but it's not really an ideal solution.
I'm curious, is there a reason we can't just point the extension towards a folder with a bunch of `.workspace` files inside of it? Normally my workspaces have a few different folders so I keep some workspace files inside Documents so I can open them easily, and since I keep my workspace folder in the same place across computers it would let me easily use this extension across multiple computers.

**Comment by Kruemelkatze** [comment]
@tkivela: I fixed your problem by using another path for that temp file (```/var/www``` on Linux). It should hopefully work now (it did for me under Ubuntu 16.04) :)

@GammaGames: The extension holds the project basically as a list of paths with a name and does not rely on .code-workspace files. To be honest, I did not think of holding a bunch of .code-workspaces before. My colleagues and me hardly use these workspace files as our projects are almost always just a single folder. 

I just released a new version (1.1) for these topics. It fixes the permission problem and provides an option to define a project by selecting a file. Projects with a path to a .code-workspace file are opened like any other folder, other file types are opened in a new tab.


Concerning using vscode-dashboard across computers: When building the extension, I thought about storing the projects in the extension's settings, so that they can by synced using [Settings Sync](https://github.com/shanalikhan/code-settings-sync).  I decided against this, as people do not necessarily have all their projects on all computers (and additionally on the same path).

**Comment by GammaGames** [comment]
> I decided against this, as people do not necessarily have all their projects on all computers (and additionally on the same path).

That's the best choice, I sync my editor settings between my work and home computer and I obviously don't have work projects at home. Letting us select a .code-workspace file is a great addition, thank you!

**Comment by Kruemelkatze** [comment]
> > I decided against this, as people do not necessarily have all their projects on all computers (and additionally on the same path).
> 
> That's the best choice, I sync my editor settings between my work and home computer and I obviously don't have work projects at home. Letting us select a .code-workspace file is a great addition, thank you!

That's the exact same setup I have. ;)

I'm closing this issue then!
