### ISSUE TITLE
Base64 code for custom icons

### ISSUE THREAD

**Issue by SheepDomination** [Kruemelkatze/vscode-dashboard#14]
I tried adding base64 code to both the `color` and `id` of a `project.json` file and and in both cases the icon was not shown ?

**Comment by Kruemelkatze** [comment]
You may add a base64 icon as an <img> take as we already discussed [in length here](https://github.com/Kruemelkatze/vscode-dashboard/issues/11#issuecomment-507453094).

However, I would not advise that, as the project data may now be saved in the user settings (if you enabled this option) and base64 icons tend to be large. And as that file is parsed quite often by VSCode, this may have side effects such as slow loading, etc.

**Comment by SheepDomination** [comment]
How is the user settings parsed, you mean changed ?

**Comment by SheepDomination** [comment]
The problem when using a Base64 icon as the `id` within the `Dashboard Projects.json` file is that I get an error that it cannot be parsed; what does this mean ?

**Comment by Kruemelkatze** [comment]
> How is the user settings parsed, you mean changed ?

Whenever it is read by VSCode, I don't know when or how often that happens, it may be whenever something is changed in the settings or some other extension requests a setting. Still, **IMHO** it's definitely not a good idea to have a file that is supposed to have a couple dozen text lines be filled with image data that may easily have a few MB.

> The problem when using a Base64 icon as the `id` within the `Dashboard Projects.json` file is that I get an error that it cannot be parsed; what does this mean ?

You get that message because your ```Dashboard Projects.json``` file does not contain valid JSON.
Possibly because you pasted some special characters or messed up the quotes.

I really don't get it why you still try to insert Base64 icons in the id or color field. If you need a custom icon, I already told you 3 times how that works. And as mentioned, you can insert/inject **any HTML** in the **project name**. If you need any fancy custom tiles, wrap the name with divs with inline styles and you can build whatever you want.

**Comment by GuentherK** [comment]
I'm also no fan of base64 as it increases size by ~34% of everything you encode with it and the dashboard config file could potentially become huge because of miss use. Extensions should not needlessly increase startup time. 
if you rly want to use icons/picture I suggest you use the unicode character instead. On Windows you can access them with **win + .**  ✨. I'm sure other OS have their ways to quickly access them too.

**Comment by SheepDomination** [comment]
Inserting a custom Unicode (emoji) is next to impossible.

**Comment by GuentherK** [comment]
I know it is not the desired solution and i might look into the code and make a pull request to implement this feature (of course with some restriction like max base64 length to force some limit to keep json file size 'small'), but in the meantime you can use _any_ emoji that chrome can render. Which are far more than windows supports with its emoji shortlist

**Comment by SheepDomination** [comment]
They won't suite my needs, I want to add a custom emoji. I'll just insert HTML to get the desired icons and look I want.
