### ISSUE TITLE
Double click to edit text

### ISSUE THREAD

**Issue by deadcoder0904** [Kruemelkatze/vscode-dashboard#20]
The pencil icon is good but I think double-click is better to start editing right away. What do you think?

**Comment by Kruemelkatze** [comment]
If the editing would be inline instead of opening VSCode's command inputs, I would agree. But for that I would need to integrate some kind of model binding into the webview (the custom HTML/JS UI that the Dashboard is built with). And I would prefer not to have too much logic in the webview itself, as custom UIs are already kind of discouraged by the VSCode devs.

So I will most likely not include that, at least for now. Sorry!
