### ISSUE TITLE
Color Dark Blue and Brown are interchanged

### ISSUE THREAD

**Issue by threeFatCat** [Kruemelkatze/vscode-dashboard#24]
When I select color Brown it apply color Dark Blue, while Dark Blue applies Brown.

**Comment by Kruemelkatze** [comment]
Are you using a custom theme?
The colors are named after how they appear in the default themes. It may look differently for you, if you use a custom theme. :)

**Comment by threeFatCat** [comment]
Yes I do, but all other colors work fine from your options, just the brown and dark blue. I'm using this theme https://material-theme.site/ Dark Ocean. Perhaps you could take a look. 

If it may look different because of theme, perhaps dark blue would not look closer to brown color? Brown and red may be closer but not Dark blue?🤷🏻‍♂️

**Comment by GuentherK** [comment]
This is definitely a 'problem' which results from using a theme. They usually overwrite buildIn colors because the original colors have bad contrast with the new color setting. 
I will try to reproduce this with a clean install on a VM

**Comment by GuentherK** [comment]
Clean install with only the dashboard extension and default light theme:

![image](https://user-images.githubusercontent.com/5037536/67599854-3b506380-f771-11e9-9ac1-bb523e19b0ca.png)

With Material Theme:

![image](https://user-images.githubusercontent.com/5037536/67600024-8b2f2a80-f771-11e9-850c-6b93b45f507f.png)

You could overwrite the themes colors as described [here](https://code.visualstudio.com/docs/getstarted/themes) but i would strongly suggest not to do so. Usually the creators of themes take great care whether they overwrite a color or not because of better contrast, etc...

It would be too much work to map for every popular theme the overwritten color to the correct name and a hexcolor lookup for the correct name via API (there are some which will tell you the name of a hexcolor value) is also not a good idea because VS Code automatically kills/deactivates all extensions which take to long to load

**Comment by Kruemelkatze** [comment]
Thanks for clarifying, @GuentherK !

What I'd like to add to that:
As the project tiles seem to have the same color as the background in this theme, I'd suggest you customize the tile color using the settings (example value, but looks good imho :) ). I have just noticed + fixed a bug in this and released v1.5.2. So thanks for your issue, I guess!

![image](https://user-images.githubusercontent.com/5564731/67602281-920c6c00-f776-11e9-9d4b-0d664ad392d5.png)

And as @GuentherK mentioned, building some kind of dynamic color name estimation or creating a custom name-color mapping for each theme is quite an overkill for a simple misnamed color. So i will just let you live with a "dark blue" looking brown, sorry! :)

**Comment by Kruemelkatze** [comment]
And just to clarify why the dashboard colors are named as they are:
The colors offered in the color dropdown are CSS-Variables inside VSCode and I selected them (out of a couple dozen colors) because they have roughly the same color across all default themes. For example, the CSS-Variable ```var(--vscode-gitDecoration-deletedResourceForeground)' ``` is red in all default themes, so I named it ```Red```. But a custom theme may as well change this color to yellow.

That's what happens in your case with blue/brown. I have now straightforward way to tell if ```var(--vscode-gitDecoration-deletedResourceForeground)``` is indeed red in your theme.
