### ISSUE TITLE
Dashboard eliminates previous workspaces with no remorse of workspace or files.

### ISSUE THREAD

**Issue by SheepDomination** [Kruemelkatze/vscode-dashboard#42]
When opening a dashboard project, my former workspace and all untitled files were completely removed and unrecoverable from what I know.  Is there any way to recover it, this has been something I've always been concerned about because whenever I load a dashboard project it takes complete control of all former workspaces and files in that workspace.  

I know I should have saved, but I had a few unsaved files for a workspace which if I can get them back & the workspace that would be good.

**Comment by Kruemelkatze** [comment]
As I've already mentioned multiple times in other issues, the extension does not handle opening projects itself. It just triggers the VSCode-native 'Open File', 'Open Folder', or 'Open Workspace' commands that are located in the File menu. No other magic happens.

This means that you have to look if VSCode backed something up. Like here: https://superuser.com/questions/1225368/visual-studio-code-unsaved-files-location/1225498

Since this behavior is native and has nothing to do with the Dashboard itself, I'll close this.
