### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by thistlillo** [Kruemelkatze/vscode-dashboard#88]
I am using your extension version v2.5.2 on VSC 
```
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043
```

The extension takes too long to load, up to 20 seconds. Is there anything I can check to speed it up or is this delay normal?

**Comment by Kruemelkatze** [comment]
Some time ago, extension devs were asked to move the extension activation to `onStartupFinished`, instead of `*` (directly on start). I think this resulted in heavily distorted startup times, dependending on configuration and other extension. With the lastest version 2.6.0,  I changed the activation back to `*` as the project dashboard doesn't require much resources to start up. So it should be a lot faster now.
